"""
MHARS — Phase 2: Learned Attention Fusion
==========================================
Replaces the hand-coded weighted average in core.py::_fuse() with a
lightweight neural self-attention module that learns cross-modal
relationships and provides attention-weight XAI.

Architecture:
  Input (6 scores) → Embed each to d_model=32
    → Self-Attention (4 heads) → Mean pool
    → Context head (32→16→1, Sigmoid)
  Returns: context, attention_weights (6×6 map for XAI)

Training data is generated by distilling the current rule-based fusion
logic plus synthetic gym environment scenarios.
"""

import os
import json
import numpy as np

try:
    import torch
    import torch.nn as nn
    from torch.utils.data import DataLoader, TensorDataset
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False


if TORCH_AVAILABLE:

    class LearnedAttentionFusion(nn.Module):
        """
        6-modality self-attention fusion with multi-head attention.
        
        Replaces the hand-coded inverse-variance weighting with a learned
        attention mechanism that captures cross-modal dependencies and provides
        interpretable attention weight maps for XAI.
        """

        MODALITY_NAMES = [
            "trend_forecast",   # LSTM score
            "pattern_check",    # AE score
            "outlier_scan",     # IF score
            "cnn_hotspot",      # CNN score
            "audio",            # Audio score
            "vibration",        # Vibration score
        ]

        def __init__(self, n_modalities=6, d_model=32, n_heads=4):
            super().__init__()
            self.n_modalities = n_modalities
            self.d_model = d_model

            # Project each modality score (scalar) to d_model dimensions
            self.modality_embeddings = nn.ModuleList([
                nn.Sequential(
                    nn.Linear(1, d_model),
                    nn.ReLU(),
                    nn.LayerNorm(d_model),
                )
                for _ in range(n_modalities)
            ])

            # Self-attention over modalities
            self.attention = nn.MultiheadAttention(
                d_model, n_heads, batch_first=True, dropout=0.1
            )
            self.layer_norm = nn.LayerNorm(d_model)

            # Context head: produces global context score ∈ [0, 1]
            self.context_head = nn.Sequential(
                nn.Linear(d_model, 16),
                nn.ReLU(),
                nn.Dropout(0.1),
                nn.Linear(16, 1),
                nn.Sigmoid(),
            )

        def forward(self, scores):
            """
            Args:
                scores: (batch, 6) — one score per modality
            Returns:
                context: (batch,) — global context score ∈ [0, 1]
                attn_weights: (batch, 6, 6) — attention map for XAI
            """
            # Embed each modality: (batch, 6, d_model)
            embedded = torch.stack([
                emb(scores[:, i:i+1])
                for i, emb in enumerate(self.modality_embeddings)
            ], dim=1)

            # Self-attention across modalities
            attended, attn_weights = self.attention(
                embedded, embedded, embedded
            )
            attended = self.layer_norm(attended + embedded)  # residual connection

            # Mean pool across modalities → (batch, d_model)
            pooled = attended.mean(dim=1)

            # Context score
            context = self.context_head(pooled).squeeze(-1)

            return context, attn_weights

        def fuse_with_xai(self, scores_np):
            """
            Convenience method for inference from numpy arrays.
            Returns context, contributions dict, top_contributor string.
            """
            self.eval()
            with torch.no_grad():
                scores_t = torch.FloatTensor(scores_np).unsqueeze(0)  # (1, 6)
                context, attn_weights = self.forward(scores_t)

            context_val = float(context.item())

            # Extract per-modality contribution from attention weights
            # Sum attention received by each modality (column-wise sum)
            attn_np = attn_weights.squeeze(0).numpy()  # (6, 6)
            importance = attn_np.sum(axis=0)  # how much attention each modality receives
            importance = importance * scores_np  # weight by actual score values

            total = importance.sum() + 1e-8
            contributions = {}
            for i, name in enumerate(self.MODALITY_NAMES):
                contributions[name] = round(float(importance[i] / total) * 100)

            top_contributor = max(contributions, key=contributions.get) if context_val > 0.05 else "none"

            return context_val, contributions, top_contributor


def generate_fusion_training_data(n_samples=10000, seed=42):
    """
    Generate labeled training data for the fusion model by:
    1. Sampling random modality score combinations
    2. Computing ground-truth context using the existing rule-based logic
    3. Adding structured scenarios (all-healthy, single-spike, multi-fault)
    
    Returns (X, y) where X is (n_samples, 6) and y is (n_samples,) context scores.
    """
    rng = np.random.RandomState(seed)
    X_list, y_list = [], []

    def rule_based_context(scores):
        """Replicate the hand-coded fusion logic as training labels."""
        weights = np.ones(6, dtype=np.float32)
        weights /= weights.sum()
        return float(np.clip(np.dot(weights, scores), 0, 1))

    # Scenario 1: Random uniform scores (~40% of data)
    n_random = int(n_samples * 0.4)
    for _ in range(n_random):
        scores = rng.uniform(0, 1, 6).astype(np.float32)
        X_list.append(scores)
        y_list.append(rule_based_context(scores))

    # Scenario 2: Healthy system (all scores low) (~15%)
    n_healthy = int(n_samples * 0.15)
    for _ in range(n_healthy):
        scores = rng.uniform(0, 0.2, 6).astype(np.float32)
        X_list.append(scores)
        y_list.append(rule_based_context(scores))

    # Scenario 3: Single modality spike (~15%)
    n_spike = int(n_samples * 0.15)
    for _ in range(n_spike):
        scores = rng.uniform(0, 0.2, 6).astype(np.float32)
        spike_idx = rng.randint(0, 6)
        scores[spike_idx] = rng.uniform(0.7, 1.0)
        X_list.append(scores)
        y_list.append(rule_based_context(scores))

    # Scenario 4: Multi-fault (2-3 modalities high) (~15%)
    n_multi = int(n_samples * 0.15)
    for _ in range(n_multi):
        scores = rng.uniform(0, 0.3, 6).astype(np.float32)
        fault_count = rng.randint(2, 4)
        fault_indices = rng.choice(6, fault_count, replace=False)
        for idx in fault_indices:
            scores[idx] = rng.uniform(0.6, 1.0)
        X_list.append(scores)
        y_list.append(rule_based_context(scores))

    # Scenario 5: Gradual degradation (~15%)
    n_degrade = n_samples - n_random - n_healthy - n_spike - n_multi
    for i in range(n_degrade):
        progress = i / max(n_degrade - 1, 1)
        base = 0.1 + progress * 0.5
        scores = rng.normal(base, 0.1, 6).astype(np.float32)
        scores = np.clip(scores, 0, 1)
        X_list.append(scores)
        y_list.append(rule_based_context(scores))

    X = np.array(X_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.float32)
    return X, y


def train_fusion_model(
    n_samples=10000,
    epochs=50,
    batch_size=64,
    lr=1e-3,
    save_path=None,
    verbose=True,
):
    """
    Train the LearnedAttentionFusion model on generated data.
    
    Returns the trained model.
    """
    if not TORCH_AVAILABLE:
        raise ImportError("PyTorch required: pip install torch")

    from mhars.config import Config
    if save_path is None:
        save_path = Config.LEARNED_FUSION_MODEL

    if verbose:
        print("── Training Learned Attention Fusion ──────────────────────────")

    # Generate training data
    X, y = generate_fusion_training_data(n_samples=n_samples)
    
    # Train/val split (80/20)
    n_train = int(len(X) * 0.8)
    X_train, y_train = X[:n_train], y[:n_train]
    X_val, y_val = X[n_train:], y[n_train:]

    train_ds = TensorDataset(torch.FloatTensor(X_train), torch.FloatTensor(y_train))
    val_ds = TensorDataset(torch.FloatTensor(X_val), torch.FloatTensor(y_val))
    train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=batch_size)

    # Initialize model
    model = LearnedAttentionFusion(
        n_modalities=Config.FUSION_N_MODALITIES,
        d_model=Config.FUSION_D_MODEL,
        n_heads=Config.FUSION_N_HEADS,
    )
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    criterion = nn.MSELoss()

    best_val_loss = float("inf")
    patience = 10
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for xb, yb in train_dl:
            optimizer.zero_grad()
            context, _ = model(xb)
            loss = criterion(context, yb)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * len(xb)
        train_loss /= len(X_train)

        # Validation
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_dl:
                context, _ = model(xb)
                val_loss += criterion(context, yb).item() * len(xb)
        val_loss /= len(X_val)

        scheduler.step()

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            torch.save(model.state_dict(), save_path)
        else:
            patience_counter += 1

        if verbose and (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1:3d}/{epochs} — "
                  f"train_loss={train_loss:.6f}, val_loss={val_loss:.6f}")

        if patience_counter >= patience:
            if verbose:
                print(f"  Early stopping at epoch {epoch+1}")
            break

    # Reload best model
    model.load_state_dict(torch.load(save_path, map_location="cpu"))
    model.eval()

    if verbose:
        print(f"  ✓  Learned Fusion saved → {save_path}")
        print(f"     Best val loss: {best_val_loss:.6f}")

    return model


if __name__ == "__main__":
    model = train_fusion_model(verbose=True)
    
    # Quick verification
    print("\n── Verification ──────────────────────────────────────────────")
    test_cases = [
        ("Healthy", np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])),
        ("LSTM spike", np.array([0.9, 0.1, 0.1, 0.1, 0.1, 0.1])),
        ("Multi-fault", np.array([0.8, 0.7, 0.6, 0.3, 0.2, 0.1])),
        ("Critical", np.array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9])),
    ]
    for name, scores in test_cases:
        ctx, contrib, top = model.fuse_with_xai(scores)
        print(f"  {name:12s}: context={ctx:.3f}, top={top}, contributions={contrib}")
"""
MHARS Learned Fusion Module
"""
