"""
MHARS — Stage 3: Physics-Informed Causal Reasoning Layer
========================================================
Uses Newton's Law of Cooling to distinguish expected heating (from load)
from unexpected heating (fault). Calculates a physics residual.
"""
import numpy as np

class PhysicsCausalLayer:
    def __init__(self, profile: dict):
        """
        Initializes with machine-specific physical parameters.
        profile: Dictionary from Config.MACHINE_PROFILES
        """
        self.profile = profile
        self.ambient_temp = 25.0
        
        # Load physical constants from profile (with defaults if missing)
        self.heat_rate = self.profile.get("heat_rate", 2.0)
        self.conv_coeff = self.profile.get("conv_coeff", 0.05)
        self.thermal_mass = self.profile.get("thermal_mass_J_K", 20.0)
        self.safe_max = self.profile.get("safe_max", 85.0)

    def analyze(self, current_temp: float, load: float, fan_speed: float = 0.0) -> dict:
        """
        Calculates causal bounds based on physics.
        current_temp: Current temperature (Celsius)
        load: Current system load [0, 1]
        fan_speed: Current fan speed [0, 1]
        
        Returns:
            dict with expected_dT, residual, root_cause_hypothesis, fault_probability
        """
        # Power In (Heat generated by load)
        q_in = self.heat_rate * load * 100.0  # arbitrary scaling factor for simulation
        
        # Power Out (Heat dissipated by cooling)
        # Fan speed increases the convection coefficient
        effective_h = self.conv_coeff * (1.0 + 2.0 * fan_speed)
        q_out = effective_h * (current_temp - self.ambient_temp) * 100.0
        
        # Expected rate of temperature change (dT/dt) based on Newton's Law
        expected_dt = (q_in - q_out) / self.thermal_mass
        
        # Since we don't have the actual previous temp easily accessible in a stateless call,
        # we estimate the expected steady-state temperature for this load & fan_speed:
        # At steady state, q_in = q_out
        # heat_rate * load = effective_h * (T_steady - T_amb)
        if effective_h > 0:
            expected_steady_temp = self.ambient_temp + (self.heat_rate * load) / effective_h
        else:
            expected_steady_temp = self.ambient_temp
            
        residual = current_temp - expected_steady_temp
        
        # Probabilistic assessment based on residual
        if residual > 15.0:
            root_cause = "External thermal anomaly (e.g., airflow blockage or bearing friction)"
            fault_prob = 1.0
        elif residual > 5.0:
            root_cause = "Cooling degradation or minor mechanical friction"
            fault_prob = 0.6
        elif current_temp > self.safe_max * 0.9:
            root_cause = "Expected physical heating due to sustained high load"
            fault_prob = 0.1
        else:
            root_cause = "Normal thermodynamic operation"
            fault_prob = 0.0
            
        return {
            "expected_steady_temp": expected_steady_temp,
            "expected_dt": expected_dt,
            "residual": residual,
            "root_cause_hypothesis": root_cause,
            "fault_probability": fault_prob
        }
